#!/usr/bin/env python3
"""
Shader System Integration Example

This example shows how to use the RISC-V random instruction generator
to create test programs for the shader system.
"""

import os
import sys
import json

# Add parent directory to path
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'src'))

from riscv_rtg.isa.riscv_isa import RISCVISA, InstructionFormat, format_hex


def generate_cpp_test_program(count=20, seed=None):
    """Generate a C++ test program with random instructions."""
    if seed is not None:
        import random
        random.seed(seed)

    isa = RISCVISA()
    instructions = isa.generate_random(count)

    print("// RISC-V test program for shader system")
    print("// Generated by riscv_rtg shader_system_integration.py")
    print("// Instructions:", count)
    if seed is not None:
        print(f"// Seed: {seed}")
    print()
    print("#include <cstdint>")
    print("#include <vector>")
    print()
    print("// Test program data")
    print("std::vector<uint32_t> test_program = {")

    for i, (encoded, asm) in enumerate(instructions):
        comment = f"  // {asm}" if asm else ""
        print(f"    0x{encoded:08x},{comment}")

    print("};")
    print()
    print("// Program entry point (example)")
    print("constexpr uint32_t ENTRY_POINT = 0x1000;")
    print()
    print("// Expected instruction count")
    print(f"constexpr size_t EXPECTED_INSTRUCTION_COUNT = {count};")

    return instructions


def generate_json_test_data(count=50, seed=None, filename=None):
    """Generate test data in JSON format for shader system tests."""
    if seed is not None:
        import random
        random.seed(seed)

    isa = RISCVISA()
    instructions = isa.generate_random(count)

    test_data = {
        "metadata": {
            "generator": "riscv_rtg",
            "instruction_set": "RV32I",
            "count": count,
            "seed": seed,
            "description": "Random RISC-V instructions for shader system testing"
        },
        "instructions": []
    }

    for encoded, asm in instructions:
        instr_data = {
            "hex": f"0x{encoded:08x}",
            "decimal": encoded,
            "binary": bin(encoded)[2:].zfill(32),
            "assembly": asm
        }
        test_data["instructions"].append(instr_data)

    json_str = json.dumps(test_data, indent=2)

    if filename:
        with open(filename, 'w') as f:
            f.write(json_str)
        print(f"Generated JSON test data saved to: {filename}")
    else:
        print(json_str)

    return test_data


def generate_instruction_stats(count=1000, seed=42):
    """Generate statistics about random instruction distribution."""
    import random
    from collections import Counter

    random.seed(seed)
    isa = RISCVISA()

    instructions = isa.generate_random(count)

    # Count by instruction name
    name_counter = Counter()
    for encoded, asm in instructions:
        if asm:
            # Extract instruction name from assembly
            name = asm.split()[0] if asm else "unknown"
            name_counter[name] += 1

    print(f"=== Instruction Distribution (n={count}, seed={seed}) ===")
    print(f"Total instructions generated: {count}")
    print()

    print("Top 20 most frequent instructions:")
    for name, freq in name_counter.most_common(20):
        percentage = (freq / count) * 100
        print(f"  {name:6}: {freq:4} ({percentage:5.1f}%)")

    print()
    print("Format distribution:")
    format_counter = Counter()
    for instr in isa.instructions:
        format_counter[instr.format.value] += 1

    for fmt, count_fmt in sorted(format_counter.items()):
        print(f"  {fmt}: {count_fmt} instructions")


def export_for_shader_system_build(count=100, seed=None):
    """Export instructions in a format suitable for shader system build integration."""
    if seed is not None:
        import random
        random.seed(seed)

    isa = RISCVISA()
    instructions = isa.generate_random(count)

    # Create directory structure
    output_dir = "shader_test_data"
    os.makedirs(output_dir, exist_ok=True)

    # 1. C++ header file
    header_path = os.path.join(output_dir, "test_program.h")
    with open(header_path, 'w') as f:
        f.write("// Auto-generated test program for shader system\n")
        f.write("// Generated by riscv_rtg\n\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstdint>\n")
        f.write("#include <array>\n\n")
        f.write("namespace shader_test {\n\n")
        f.write(f"constexpr size_t TEST_PROGRAM_SIZE = {count};\n\n")
        f.write("constexpr std::array<uint32_t, TEST_PROGRAM_SIZE> TEST_PROGRAM = {{\n")
        for encoded, asm in instructions:
            f.write(f"    0x{encoded:08x},\n")
        f.write("}};\n\n")
        f.write("} // namespace shader_test\n")

    # 2. Assembly file (for reference)
    asm_path = os.path.join(output_dir, "test_program.s")
    with open(asm_path, 'w') as f:
        f.write("# Test program assembly (for reference only)\n")
        f.write("# Generated by riscv_rtg\n\n")
        f.write(".text\n")
        f.write(".globl _start\n")
        f.write("_start:\n")
        for i, (encoded, asm) in enumerate(instructions):
            f.write(f"    # 0x{encoded:08x}\n")
            if asm:
                f.write(f"    {asm}\n")
            else:
                f.write(f"    .word 0x{encoded:08x}\n")
            if (i + 1) % 5 == 0:
                f.write("\n")

    # 3. Python verification script
    py_path = os.path.join(output_dir, "verify_program.py")
    with open(py_path, 'w') as f:
        f.write("#!/usr/bin/env python3\n")
        f.write('"""\n')
        f.write("Verification script for generated test program.\n")
        f.write("Compares Python-generated instructions with C++ decoding.\n")
        f.write('"""\n\n')
        f.write("import sys\n")
        f.write("import os\n")
        f.write("sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))\n\n")
        f.write("from riscv_rtg.isa.riscv_isa import RISCVISA\n\n")
        f.write("def main():\n")
        f.write(f"    isa = RISCVISA()\n")
        f.write(f"    print(f'Verifying {count} instructions...')\n")
        f.write("    \n")
        f.write("    # Re-generate with same seed\n")
        if seed is not None:
            f.write(f"    import random\n")
            f.write(f"    random.seed({seed})\n")
        f.write("    \n")
        f.write("    instructions = isa.generate_random(count)\n")
        f.write("    \n")
        f.write("    print('First 5 instructions:')\n")
        f.write("    for i, (encoded, asm) in enumerate(instructions[:5]):\n")
        f.write("        print(f'  {i}: 0x{encoded:08x} {asm}')\n")
        f.write("    \n")
        f.write("    print(f'\\nVerification complete. {len(instructions)} instructions generated.')\n")
        f.write("    \n")
        f.write("if __name__ == '__main__':\n")
        f.write("    main()\n")

    os.chmod(py_path, 0o755)

    print(f"Generated shader system test data in: {output_dir}")
    print(f"  - {header_path}: C++ header file")
    print(f"  - {asm_path}: Assembly reference")
    print(f"  - {py_path}: Python verification script")
    print(f"\nTo use in shader system:")
    print(f"  1. Copy {header_path} to shader system include directory")
    print(f"  2. Include in CMakeLists.txt")
    print(f"  3. Run verification: python3 {py_path}")


def main():
    """Main example function."""
    print("=" * 70)
    print("RISC-V Random Instruction Generator - Shader System Integration")
    print("=" * 70)
    print()

    # Example 1: Generate C++ test program
    print("Example 1: Generating C++ Test Program")
    print("-" * 40)
    generate_cpp_test_program(count=10, seed=12345)
    print()

    # Example 2: Generate JSON test data
    print("\nExample 2: Generating JSON Test Data")
    print("-" * 40)
    json_data = generate_json_test_data(count=5, seed=42, filename=None)
    print("(JSON output truncated for brevity)")
    print()

    # Example 3: Instruction statistics
    print("\nExample 3: Instruction Statistics")
    print("-" * 40)
    generate_instruction_stats(count=500, seed=42)
    print()

    # Example 4: Full export for shader system
    print("\nExample 4: Export for Shader System Build")
    print("-" * 40)
    print("This would generate files in 'shader_test_data/' directory.")
    print("Uncomment the function call below to run.")
    # export_for_shader_system_build(count=50, seed=42)
    print()

    print("=" * 70)
    print("Integration examples complete.")
    print("\nNext steps for shader system integration:")
    print("1. Use generate_cpp_test_program() to create test vectors")
    print("2. Include generated headers in shader system tests")
    print("3. Use JSON export for cross-language test data")
    print("4. Run statistical analysis to verify instruction distribution")
    print("=" * 70)


if __name__ == '__main__':
    main()